---
- name: Configure DNS with systemd-resolved
  hosts: all
  become: yes

  tasks:
    - name: Set Google DNS in resolved.conf
      community.general.ini_file:
        path: /etc/systemd/resolved.conf
        section: Resolve
        option: DNS
        value: '8.8.8.8'
        mode: '0644'
      notify: Restart systemd-resolved

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
